apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: efk
spec:
  version: 8.17.0
  count: 1
  elasticsearchRef:
    name: elasticsearch-test
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
  http:
    service:
      spec:
        type: LoadBalancer
