apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: application-pool
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
      - name: logger
        image: busybox
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "$(date) - Random log: $RANDOM"
            sleep 100
          done
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
